### ISSUE TITLE
NoMethodError if no input is passed to ORI::Internals.choice

### ISSUE THREAD

**Issue by ab** [dadooda/ori#1]
The `gets` method will return `nil` if the user presses `ctrl+d` to trigger an EOF. This causes a NoMethodError on line 144 when `gets.strip` is run.

```
>> ORI::Internals.choice([['foo', 1]])
  1 foo

>> NoMethodError: undefined method `strip' for nil:NilClass
    from /var/lib/gems/1.8/gems/ori-0.1.0/lib/ori/internals.rb:144:in `choice'
    from (irb):139
    from :0
```

**Comment by dadooda** [comment]
Andy

Thanks for the report. I'll fix the issue in a while. At the moment you can push CtrlC if you want to abort the choice. It should work.

**Comment by dadooda** [comment]
Andy

FYI

Just in case you may think it's worth it, you could give a vote up to ORI post at stackoverflow: http://stackoverflow.com/questions/123494/whats-your-favourite-irb-trick/4607243#4607243.

I've got no time to promote the solution full bore, but I certainly want to share it with more people since I think it's really a productivity breakthrough.
